spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  datasource:
    url: jdbc:h2:tcp://localhost/~/appcenterstudy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    open-in-view: false

cloud:
  aws:
    credentials:
      accessKey:  # TODO
      secretKey:  # TODO
    s3:
      bucket: inu-appcenter-study-bucket-dskim
      thumbnailBucket: inu-appcenter-study-bucket-thumbnail-dskim
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace